# Generated by Django 5.2.4 on 2025-12-07 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
