# Generated by Django 5.2.4 on 2025-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_analysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
