# Generated by Django 5.2.4 on 2025-12-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_analysis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='image_path',
            field=models.CharField(null=True),
        ),
    ]
