# Generated by Django 5.2.4 on 2025-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_analysis_data_alter_analysis_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='type',
            field=models.IntegerField(choices=[(0, 'Similar players'), (1, 'Predict player performance'), (2, 'Predict team outcome')], default=0),
            preserve_default=False,
        ),
    ]
