# Generated by Django 5.2.4 on 2025-12-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_analysis_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='user id',
            new_name='user_id',
        ),
    ]
