# Generated by Django 5.2.4 on 2025-12-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_user_id_analysis_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='date',
        ),
    ]
