# Generated by Django 5.2.4 on 2025-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_analysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='final_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='team_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
