# Generated by Django 5.2.4 on 2025-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_analysis_final_index_analysis_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='fixture_name',
            field=models.TextField(null=True),
        ),
    ]
